export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS mayors (
    id TEXT PRIMARY KEY,
    country_ar TEXT NOT NULL,
    city_ar TEXT NOT NULL,
    city_en TEXT NOT NULL,
    title_ar TEXT NOT NULL,
    title_en TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_native TEXT NOT NULL,
    name_ar TEXT NOT NULL,
    native_lang TEXT NOT NULL,
    native_lang_ar TEXT NOT NULL,
    country_code TEXT NOT NULL,
    gn_hl TEXT NOT NULL,
    gn_gl TEXT NOT NULL,
    official_host TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS scans (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    query TEXT,
    mayor_id TEXT,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    found_count INTEGER DEFAULT 0,
    duplicate_count INTEGER DEFAULT 0,
    excluded_count INTEGER DEFAULT 0,
    error_count INTEGER DEFAULT 0,
    notes TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS items (
    id TEXT PRIMARY KEY,
    mayor_id TEXT NOT NULL,
    scan_id TEXT,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    title_normalized TEXT NOT NULL,
    url TEXT NOT NULL,
    published_at TEXT,
    snippet TEXT,
    title_ar TEXT,
    snippet_ar TEXT,
    language TEXT,
    confidence TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'inbox',
    exclude_reason TEXT,
    fingerprint TEXT NOT NULL,
    trans_engine TEXT,
    publisher_domain TEXT,
    publisher_tier INTEGER,
    article_text TEXT,
    source_documents TEXT,
    merged_sources TEXT,
    source_count INTEGER DEFAULT 1,
    brief_evidence TEXT,
    brief_error TEXT,
    brief_attempted_at TEXT,
    brief_attempts INTEGER DEFAULT 0,
    brief_claim_id TEXT,
    brief_claimed_at TEXT,
    brief_after TEXT,
    brief_provider TEXT,
    desk_lane TEXT,
    desk_attention_reason TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`,
  `CREATE INDEX IF NOT EXISTS idx_items_status ON items(status, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_items_scan ON items(scan_id)`,
  `CREATE INDEX IF NOT EXISTS idx_items_mayor ON items(mayor_id)`,
  `CREATE INDEX IF NOT EXISTS idx_items_brief_lane ON items(brief_provider, trans_engine)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_items_fingerprint ON items(fingerprint)`,
  `CREATE INDEX IF NOT EXISTS idx_scans_started ON scans(started_at DESC)`,
  `CREATE TABLE IF NOT EXISTS search_jobs (
    id TEXT PRIMARY KEY,
    query TEXT,
    mayor_id TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    created_at TEXT DEFAULT (datetime('now')),
    finished_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS search_job_tasks (
    job_id TEXT NOT NULL,
    mayor_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    attempts INTEGER DEFAULT 0,
    stage TEXT DEFAULT 'queued',
    detail TEXT,
    started_at TEXT,
    finished_at TEXT,
    result_json TEXT,
    error TEXT,
    PRIMARY KEY (job_id, mayor_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_search_job_tasks_status
    ON search_job_tasks(job_id, status)`,
  `CREATE TABLE IF NOT EXISTS publishers (
    id TEXT PRIMARY KEY,
    domain TEXT NOT NULL,
    name TEXT NOT NULL,
    tier INTEGER NOT NULL,
    country_code TEXT,
    mayor_id TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_publishers_domain ON publishers(domain)`,
  `CREATE TABLE IF NOT EXISTS sources (
    id TEXT PRIMARY KEY,
    mayor_id TEXT NOT NULL,
    domain TEXT NOT NULL,
    name TEXT NOT NULL,
    tier INTEGER NOT NULL,
    kind TEXT NOT NULL,
    url TEXT NOT NULL,
    rank INTEGER NOT NULL,
    verified INTEGER DEFAULT 0,
    curated_at TEXT,
    last_checked_at TEXT,
    last_ok_at TEXT,
    last_status TEXT,
    last_items INTEGER DEFAULT 0,
    consecutive_failures INTEGER DEFAULT 0,
    enabled INTEGER DEFAULT 1,
    connect_status TEXT,
    http_status INTEGER,
    parse_status TEXT,
    discovered_count INTEGER DEFAULT 0,
    new_count INTEGER DEFAULT 0,
    read_count INTEGER DEFAULT 0,
    relevant_count INTEGER DEFAULT 0,
    last_success_at TEXT,
    last_discovery_at TEXT,
    last_fresh_at TEXT,
    fail_reason TEXT,
    last_strategy TEXT,
    last_discovered_url TEXT,
    etag TEXT,
    last_modified TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sources_mayor ON sources(mayor_id, rank)`,
  `CREATE TABLE IF NOT EXISTS candidates (
    id TEXT PRIMARY KEY,
    mayor_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    scan_id TEXT,
    url TEXT NOT NULL,
    canonical_url TEXT,
    title TEXT,
    snippet TEXT,
    published_at TEXT,
    discovered_at TEXT NOT NULL,
    discovery_type TEXT,
    stage TEXT NOT NULL DEFAULT 'candidate_discovered',
    fetch_status TEXT NOT NULL DEFAULT 'pending',
    http_status INTEGER,
    skip_reason TEXT,
    etag TEXT,
    last_modified TEXT,
    fetched_at TEXT,
    attempts INTEGER DEFAULT 0
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_candidates_source_url ON candidates(source_id, url)`,
  `CREATE INDEX IF NOT EXISTS idx_candidates_fetch ON candidates(fetch_status, mayor_id)`,
  `CREATE INDEX IF NOT EXISTS idx_candidates_scan ON candidates(scan_id)`,
  `CREATE TABLE IF NOT EXISTS settings_audit (
    id TEXT PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    source_id TEXT,
    mayor_id TEXT,
    before_json TEXT,
    after_json TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS scan_sources (
    scan_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    mayor_id TEXT NOT NULL,
    job_id TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    detail TEXT,
    PRIMARY KEY (scan_id, source_id)
  )`,
  `CREATE TABLE IF NOT EXISTS ai_budget (
    day TEXT PRIMARY KEY,
    calls INTEGER NOT NULL DEFAULT 0,
    last_call_at TEXT,
    blocked_until TEXT,
    block_reason TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS ai_provider_budget (
    day TEXT NOT NULL,
    provider TEXT NOT NULL,
    calls INTEGER NOT NULL DEFAULT 0,
    last_call_at TEXT,
    blocked_until TEXT,
    block_reason TEXT,
    PRIMARY KEY (day, provider)
  )`,
  `CREATE TABLE IF NOT EXISTS meta (
    k TEXT PRIMARY KEY,
    v TEXT
  )`,
];

export const REQUIRED_TABLES = [
  "mayors",
  "items",
  "scans",
  "search_jobs",
  "search_job_tasks",
  "publishers",
  "sources",
  "candidates",
  "settings_audit",
  "scan_sources",
  "ai_budget",
  "ai_provider_budget",
  "brief_versions",
  "approvals",
];
