/** المرحلة 1: 12 عمدة. الرصد = الاسم الإنجليزي + لغة الأم. العربي للعرض فقط. */
export const MAYORS = [
  {
    id: "seoul",
    country_ar: "كوريا الجنوبية",
    city_ar: "سيئول",
    city_en: "Seoul",
    title_ar: "عمدة سيئول",
    title_en: "Mayor of Seoul",
    name_en: "Oh Se-hoon",
    name_native: "오세훈",
    name_ar: "أوه سيه هون",
    native_lang: "ko",
    native_lang_ar: "الكورية",
    country_code: "KR",
    gn_hl: "ko",
    gn_gl: "KR",
    official_host: "seoul.go.kr",
  },
  {
    id: "madrid",
    country_ar: "إسبانيا",
    city_ar: "مدريد",
    city_en: "Madrid",
    title_ar: "عمدة مدريد",
    title_en: "Mayor of Madrid",
    name_en: "José Luis Martínez-Almeida",
    name_native: "José Luis Martínez-Almeida",
    name_ar: "خوسيه لويس مارتينيز ألميدا",
    native_lang: "es",
    native_lang_ar: "الإسبانية",
    country_code: "ES",
    gn_hl: "es",
    gn_gl: "ES",
    official_host: "madrid.es",
  },
  {
    id: "northeast-england",
    country_ar: "المملكة المتحدة",
    city_ar: "شمال شرق إنجلترا",
    city_en: "North East England",
    title_ar: "عمدة إقليم شمال شرق إنجلترا",
    title_en: "Mayor of the North East",
    name_en: "Kim McGuinness",
    name_native: "Kim McGuinness",
    name_ar: "كيم ماكغينيس",
    native_lang: "en",
    native_lang_ar: "الإنجليزية",
    country_code: "GB",
    gn_hl: "en-GB",
    gn_gl: "GB",
    official_host: "northeast-ca.gov.uk",
  },
  {
    id: "amman",
    country_ar: "الأردن",
    city_ar: "عمّان",
    city_en: "Amman",
    title_ar: "أمين عمّان الكبرى",
    title_en: "Mayor of Greater Amman",
    name_en: "Yousef Al-Shawarbeh",
    name_native: "يوسف الشواربة",
    name_ar: "د. يوسف الشواربة",
    native_lang: "ar",
    native_lang_ar: "العربية",
    country_code: "JO",
    gn_hl: "ar",
    gn_gl: "JO",
    official_host: "ammancity.gov.jo",
  },
  {
    id: "baghdad",
    country_ar: "العراق",
    city_ar: "بغداد",
    city_en: "Baghdad",
    title_ar: "أمين بغداد",
    title_en: "Mayor of Baghdad",
    name_en: "Ammar Musa Kadhim",
    name_native: "عمار موسى كاظم",
    name_ar: "عمار موسى كاظم",
    native_lang: "ar",
    native_lang_ar: "العربية",
    country_code: "IQ",
    gn_hl: "ar",
    gn_gl: "IQ",
    official_host: "amanatbaghdad.gov.iq",
  },
  {
    id: "muscat",
    country_ar: "سلطنة عُمان",
    city_ar: "مسقط",
    city_en: "Muscat",
    title_ar: "رئيس بلدية مسقط",
    title_en: "Chairman of Muscat Municipality",
    name_en: "Ahmed bin Mohammed Al-Humaidi",
    name_native: "أحمد بن محمد الحميدي",
    name_ar: "أحمد بن محمد الحميدي",
    native_lang: "ar",
    native_lang_ar: "العربية",
    country_code: "OM",
    gn_hl: "ar",
    gn_gl: "OM",
    official_host: "mm.gov.om",
  },
  {
    id: "malaga",
    country_ar: "إسبانيا",
    city_ar: "مالقة",
    city_en: "Malaga",
    title_ar: "عمدة مالقة",
    title_en: "Mayor of Malaga",
    name_en: "Francisco de la Torre",
    name_native: "Francisco de la Torre",
    name_ar: "فرانسيسكو دي لا توري",
    native_lang: "es",
    native_lang_ar: "الإسبانية",
    country_code: "ES",
    gn_hl: "es",
    gn_gl: "ES",
    official_host: "malaga.eu",
  },
  {
    id: "pristina",
    country_ar: "كوسوفو",
    city_ar: "بريشتينا",
    city_en: "Pristina",
    title_ar: "عمدة بريشتينا",
    title_en: "Mayor of Pristina",
    name_en: "Perparim Rama",
    name_native: "Përparim Rama",
    name_ar: "بيرباريم راما",
    native_lang: "sq",
    native_lang_ar: "الألبانية",
    country_code: "XK",
    gn_hl: "en",
    gn_gl: "US",
    official_host: "prishtinaonline.com",
  },
  {
    id: "turin",
    country_ar: "إيطاليا",
    city_ar: "تورينو",
    city_en: "Turin",
    title_ar: "عمدة تورينو",
    title_en: "Mayor of Turin",
    name_en: "Stefano Lo Russo",
    name_native: "Stefano Lo Russo",
    name_ar: "ستيفانو لو روسو",
    native_lang: "it",
    native_lang_ar: "الإيطالية",
    country_code: "IT",
    gn_hl: "it",
    gn_gl: "IT",
    official_host: "comune.torino.it",
  },
  {
    id: "osaka",
    country_ar: "اليابان",
    city_ar: "أوساكا",
    city_en: "Osaka",
    title_ar: "عمدة مدينة أوساكا",
    title_en: "Mayor of Osaka",
    name_en: "Hideyuki Yokoyama",
    name_native: "横山英幸",
    name_ar: "هيدييوكي يوكوياما",
    native_lang: "ja",
    native_lang_ar: "اليابانية",
    country_code: "JP",
    gn_hl: "ja",
    gn_gl: "JP",
    official_host: "city.osaka.lg.jp",
  },
  {
    id: "rabat",
    country_ar: "المغرب",
    city_ar: "الرباط",
    city_en: "Rabat",
    title_ar: "عمدة الرباط",
    title_en: "Mayor of Rabat",
    name_en: "Fatiha El Moudni",
    name_native: "فتيحة المودني",
    name_ar: "فتيحة المودني",
    native_lang: "ar",
    native_lang_ar: "العربية",
    country_code: "MA",
    gn_hl: "ar",
    gn_gl: "MA",
    official_host: "rabat.ma",
  },
  {
    id: "athens",
    country_ar: "اليونان",
    city_ar: "أثينا",
    city_en: "Athens",
    title_ar: "عمدة أثينا",
    title_en: "Mayor of Athens",
    name_en: "Haris Doukas",
    name_native: "Χάρης Δούκας",
    name_ar: "هاريس دوكاس",
    native_lang: "el",
    native_lang_ar: "اليونانية",
    country_code: "GR",
    gn_hl: "el",
    gn_gl: "GR",
    official_host: "cityofathens.gr",
  },
];

export function mayorById(id) {
  return MAYORS.find((m) => m.id === id) || null;
}

export function buildSearchQueries(mayor, extra = "") {
  const extraBit = String(extra || "").trim();
  const nameClause =
    mayor.name_en === mayor.name_native
      ? `"${mayor.name_en}"`
      : `("${mayor.name_en}" OR "${mayor.name_native}")`;
  const base = extraBit ? `${nameClause} ${extraBit}` : `${nameClause} "${mayor.city_en}"`;
  const official = mayor.official_host
    ? `${nameClause} site:${mayor.official_host}`
    : null;
  return {
    native: base,
    english: extraBit
      ? `"${mayor.name_en}" ${extraBit}`
      : `"${mayor.name_en}" "${mayor.title_en}"`,
    official,
  };
}

export function relevanceTokens(mayor) {
  const parts = [
    mayor.name_en,
    mayor.name_native,
    mayor.city_en,
    mayor.city_ar,
    mayor.title_en,
    "mayor",
    "alcalde",
    "sindaco",
    "δήμαρχος",
    "시장",
    "市長",
    "أمين",
    "عمدة",
    "بلدية",
  ];
  return parts
    .flatMap((p) => String(p).split(/[\s,."()]+/))
    .map((t) => t.trim().toLowerCase())
    .filter((t) => t.length >= 3);
}
